export default {
    LOAD_COURSES : "LOAD_COURSES",
    LOAD_COURSE_BY_SLUG : "LOAD_COURSE_BY_SLUG",
    ADD_COURSE : "ADD_COURSE",
    UPDATE_COURSE : "UPDATE_COURSE",
    DELETE_COURSE : "DELETE_COURSE",
}